"use client";

import { useState } from "react";
import type { AnalysisResult, CategoryResult, Finding } from "@/lib/types";

function generateMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];
  const ratingEmoji =
    result.rating === "excellent"
      ? "A+"
      : result.rating === "good"
        ? "A"
        : result.rating === "needs-work"
          ? "B"
          : "C";

  lines.push(`# GEOScore Report: ${result.pageTitle || result.url}`);
  lines.push("");
  lines.push(`**URL:** ${result.url}`);
  lines.push(`**Overall Score:** ${Math.round(result.overallScore)}/100 (${ratingEmoji} — ${result.rating.replace("-", " ")})`);
  lines.push(`**Industry:** ${result.industry}`);
  lines.push(`**Analyzed:** ${new Date(result.fetchedAt).toLocaleString()}`);
  lines.push("");

  lines.push("## Quick Stats");
  lines.push("");
  lines.push(`- Words: ${result.metadata.wordCount.toLocaleString()}`);
  lines.push(`- Headings: ${result.metadata.headingCount}`);
  lines.push(`- Images: ${result.metadata.imageCount}`);
  lines.push(`- Lists: ${result.metadata.listCount}`);
  lines.push(`- Tables: ${result.metadata.tableCount}`);
  lines.push(`- FAQ sections: ${result.metadata.faqCount}`);
  lines.push(`- Schema types: ${result.metadata.schemaTypes.join(", ") || "None"}`);
  lines.push(`- robots.txt: ${result.metadata.hasRobotsTxt ? "Found" : "Missing"}`);
  lines.push(`- llms.txt: ${result.metadata.hasLlmsTxt ? "Found" : "Missing"}`);
  lines.push(`- Sitemap: ${result.metadata.hasSitemap ? "Found" : "Missing"}`);
  lines.push("");

  lines.push("## Category Breakdown");
  lines.push("");
  const sorted = [...result.categories].sort((a, b) => b.weight - a.weight);
  for (const cat of sorted) {
    lines.push(`### ${cat.name} — ${cat.score}/10 (weight: ${cat.weight}%)`);
    lines.push("");
    for (const f of cat.findings) {
      const icon =
        f.type === "good" ? "[PASS]" : f.type === "critical" ? "[CRITICAL]" : f.type === "warning" ? "[WARNING]" : "[INFO]";
      lines.push(`- ${icon} ${f.message}`);
    }
    if (cat.fixes.length > 0) {
      lines.push("");
      lines.push("**Fixes:**");
      for (const fix of cat.fixes) {
        lines.push(`- (${fix.priority}) ${fix.title}: ${fix.description}`);
      }
    }
    lines.push("");
  }

  if (result.generatedFixes.contentRecommendations.length > 0) {
    lines.push("## Content Recommendations");
    lines.push("");
    for (const rec of result.generatedFixes.contentRecommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push("");
  }

  if (result.generatedFixes.jsonLd) {
    lines.push("## Fix: JSON-LD Structured Data");
    lines.push("");
    lines.push("```json");
    lines.push(result.generatedFixes.jsonLd);
    lines.push("```");
    lines.push("");
  }
  if (result.generatedFixes.metaTags) {
    lines.push("## Fix: Meta Tags");
    lines.push("");
    lines.push("```html");
    lines.push(result.generatedFixes.metaTags);
    lines.push("```");
    lines.push("");
  }
  if (result.generatedFixes.robotsTxt) {
    lines.push("## Fix: robots.txt");
    lines.push("");
    lines.push("```");
    lines.push(result.generatedFixes.robotsTxt);
    lines.push("```");
    lines.push("");
  }
  if (result.generatedFixes.llmsTxt) {
    lines.push("## Fix: llms.txt");
    lines.push("");
    lines.push("```");
    lines.push(result.generatedFixes.llmsTxt);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [GEOScore](https://geoscore.sucana.ai) — AI Search Visibility Analyzer by Sucana AI*");

  return lines.join("\n");
}

function downloadMarkdown(result: AnalysisResult) {
  const md = generateMarkdown(result);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const hostname = new URL(result.url).hostname.replace(/\./g, "-");
  a.href = url;
  a.download = `geoscore-${hostname}-${Math.round(result.overallScore)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

function ScoreDonut({ score, rating }: { score: number; rating: string }) {
  const circumference = 2 * Math.PI * 54;
  const offset = circumference - (score / 100) * circumference;
  const strokeColor =
    score >= 80
      ? "#16a34a"
      : score >= 60
        ? "#ca8a04"
        : score >= 40
          ? "#ea580c"
          : "#ef4444";

  return (
    <div className="flex flex-col items-center gap-3">
      <div className="relative h-36 w-36">
        <svg className="h-full w-full -rotate-90" viewBox="0 0 120 120">
          <circle
            cx="60"
            cy="60"
            r="54"
            fill="none"
            stroke="#f3f4f6"
            strokeWidth="8"
          />
          <circle
            cx="60"
            cy="60"
            r="54"
            fill="none"
            stroke={strokeColor}
            strokeWidth="8"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="text-3xl font-extrabold text-gray-900">{Math.round(score)}</span>
        </div>
      </div>
      <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold capitalize text-gray-600">
        {rating.replace("-", " ")}
      </span>
    </div>
  );
}

function FindingBadge({ type }: { type: Finding["type"] }) {
  const styles = {
    good: "bg-green-50 text-green-700",
    warning: "bg-yellow-50 text-yellow-700",
    critical: "bg-red-50 text-red-700",
    info: "bg-blue-50 text-blue-700",
  };
  const labels = {
    good: "Pass",
    warning: "Warning",
    critical: "Critical",
    info: "Info",
  };

  return (
    <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-semibold ${styles[type]}`}>
      {labels[type]}
    </span>
  );
}

function CategoryCard({ category, index }: { category: CategoryResult; index: number }) {
  const [open, setOpen] = useState(index < 3);
  const barColor =
    category.score >= 8
      ? "bg-green-500"
      : category.score >= 5
        ? "bg-yellow-500"
        : category.score >= 3
          ? "bg-orange-500"
          : "bg-red-500";

  return (
    <div className="rounded-2xl border border-gray-100 bg-white transition-all duration-300 hover:shadow-lg">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between p-5 text-left"
      >
        <div>
          <span className="font-semibold text-gray-900">{category.name}</span>
          <span className="ml-2 text-xs text-gray-400">Weight: {category.weight}%</span>
        </div>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <div className="h-2 w-20 overflow-hidden rounded-full bg-gray-100">
              <div
                className={`h-full rounded-full ${barColor}`}
                style={{ width: `${(category.score / 10) * 100}%` }}
              />
            </div>
            <span className="w-10 text-right text-sm font-bold text-gray-900">
              {category.score}/10
            </span>
          </div>
          <svg
            className={`h-4 w-4 text-gray-400 transition-transform ${open ? "rotate-180" : ""}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </button>

      {open && (
        <div className="border-t border-gray-100 px-5 pb-5 pt-4">
          <ul className="space-y-2">
            {category.findings.map((f, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <FindingBadge type={f.type} />
                <span className="text-gray-600">{f.message}</span>
              </li>
            ))}
          </ul>

          {category.fixes.length > 0 && (
            <div className="mt-4">
              <h4 className="text-xs font-semibold uppercase tracking-widest text-gray-400 mb-2">
                Recommended Fixes
              </h4>
              <ul className="space-y-2">
                {category.fixes.map((fix, i) => (
                  <li key={i} className="rounded-2xl bg-gray-50 p-4 text-sm">
                    <div className="flex items-center gap-2">
                      <span
                        className={`rounded-full px-2 py-0.5 text-xs font-semibold ${
                          fix.priority === "critical"
                            ? "bg-red-50 text-red-700"
                            : fix.priority === "medium"
                              ? "bg-yellow-50 text-yellow-700"
                              : "bg-gray-100 text-gray-500"
                        }`}
                      >
                        {fix.priority}
                      </span>
                      <span className="font-semibold text-gray-900">{fix.title}</span>
                    </div>
                    <p className="mt-1 text-gray-500">{fix.description}</p>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function CodeBlock({ title, code, language }: { title: string; code: string; language: string }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="rounded-2xl border border-gray-100 bg-white overflow-hidden">
      <div className="flex items-center justify-between border-b border-gray-100 px-5 py-3">
        <span className="text-sm font-semibold text-gray-900">{title}</span>
        <div className="flex items-center gap-2">
          <span className="rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-500">
            {language}
          </span>
          <button
            onClick={handleCopy}
            className="rounded-full px-3 py-1 text-xs font-semibold text-purple-500 transition-colors hover:bg-purple-50"
          >
            {copied ? "Copied!" : "Copy"}
          </button>
        </div>
      </div>
      <pre className="overflow-x-auto bg-gray-50 p-5 text-xs leading-relaxed text-gray-700">
        <code>{code}</code>
      </pre>
    </div>
  );
}

export default function Report({
  result,
  id,
  internalLinks,
  analyzedUrls,
  onAnalyzeLink,
  isAnalyzing,
  analyzingUrl,
}: {
  result: AnalysisResult;
  id?: string;
  internalLinks?: { href: string; text: string }[];
  analyzedUrls?: Set<string>;
  onAnalyzeLink?: (url: string) => void;
  isAnalyzing?: boolean;
  analyzingUrl?: string | null;
}) {
  const [linkCopied, setLinkCopied] = useState(false);

  function handleCopyLink() {
    if (!id) return;
    const shareUrl = `${window.location.origin}/report/${id}`;
    navigator.clipboard.writeText(shareUrl);
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
  }

  return (
    <section className="space-y-8">
      {/* Action buttons */}
      <div className="flex flex-wrap gap-3 justify-end">
        <button
          onClick={() => downloadMarkdown(result)}
          className="inline-flex items-center gap-2 rounded-full border border-gray-200 bg-white px-5 py-2.5 text-sm font-semibold text-gray-600 shadow-sm transition-colors hover:border-purple-200 hover:text-purple-600"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download Markdown
        </button>
        {id && (
          <button
            onClick={handleCopyLink}
            className="inline-flex items-center gap-2 rounded-full bg-purple-500 px-5 py-2.5 text-sm font-bold text-white transition-colors hover:bg-purple-600"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
            </svg>
            {linkCopied ? "Link Copied!" : "Share Report"}
          </button>
        )}
      </div>

      {/* Header */}
      <div className="flex flex-col items-center gap-6 rounded-2xl border border-gray-100 bg-white p-8 sm:flex-row sm:items-start">
        <ScoreDonut score={result.overallScore} rating={result.rating} />
        <div className="flex-1 text-center sm:text-left">
          <h2 className="text-2xl font-bold text-gray-900">{result.pageTitle || result.url}</h2>
          <p className="mt-1 text-sm text-gray-400 break-all">{result.url}</p>
          <div className="mt-3 flex flex-wrap justify-center gap-2 sm:justify-start">
            <span className="rounded-full bg-purple-50 px-3 py-1 text-xs font-semibold text-purple-500">
              {result.industry}
            </span>
            <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-500">
              {result.metadata.wordCount.toLocaleString()} words
            </span>
            <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-500">
              {result.metadata.headingCount} headings
            </span>
            <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-500">
              {result.metadata.schemaTypes.length} schemas
            </span>
          </div>
          <div className="mt-3 flex flex-wrap justify-center gap-4 text-xs text-gray-400 sm:justify-start">
            <span>
              robots.txt:{" "}
              <strong className={result.metadata.hasRobotsTxt ? "text-green-600" : "text-red-500"}>
                {result.metadata.hasRobotsTxt ? "Found" : "Missing"}
              </strong>
            </span>
            <span>
              llms.txt:{" "}
              <strong className={result.metadata.hasLlmsTxt ? "text-green-600" : "text-red-500"}>
                {result.metadata.hasLlmsTxt ? "Found" : "Missing"}
              </strong>
            </span>
            <span>
              Sitemap:{" "}
              <strong className={result.metadata.hasSitemap ? "text-green-600" : "text-red-500"}>
                {result.metadata.hasSitemap ? "Found" : "Missing"}
              </strong>
            </span>
          </div>
        </div>
      </div>

      {/* Categories */}
      <div>
        <h2 className="mb-4 text-xl font-bold text-gray-900">Category Breakdown</h2>
        <div className="space-y-3">
          {[...result.categories]
            .sort((a, b) => b.weight - a.weight)
            .map((cat, i) => (
              <CategoryCard key={cat.name} category={cat} index={i} />
            ))}
        </div>
      </div>

      {/* Content Recommendations */}
      {result.generatedFixes.contentRecommendations.length > 0 && (
        <div>
          <h2 className="mb-4 text-xl font-bold text-gray-900">Content Recommendations</h2>
          <div className="rounded-2xl border border-gray-100 bg-white p-6">
            <ul className="space-y-3">
              {result.generatedFixes.contentRecommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-3 text-sm">
                  <span className="mt-0.5 text-purple-500">&#8226;</span>
                  <span className="text-gray-600">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Generated Fix Code */}
      <div>
        <h2 className="mb-4 text-xl font-bold text-gray-900">Generated Fix Code</h2>
        <div className="space-y-4">
          {result.generatedFixes.jsonLd && (
            <CodeBlock title="JSON-LD Structured Data" code={result.generatedFixes.jsonLd} language="json" />
          )}
          {result.generatedFixes.metaTags && (
            <CodeBlock title="Meta Tags" code={result.generatedFixes.metaTags} language="html" />
          )}
          {result.generatedFixes.robotsTxt && (
            <CodeBlock title="robots.txt Rules" code={result.generatedFixes.robotsTxt} language="text" />
          )}
          {result.generatedFixes.llmsTxt && (
            <CodeBlock title="llms.txt" code={result.generatedFixes.llmsTxt} language="text" />
          )}
        </div>
      </div>

      {/* Internal Links — Pages found */}
      {internalLinks && internalLinks.length > 0 && onAnalyzeLink && (
        <div>
          <h2 className="mb-4 text-xl font-bold text-gray-900">
            Pages found on this site
          </h2>
          <p className="mb-4 text-sm text-gray-500">
            We found {internalLinks.length} internal link{internalLinks.length !== 1 ? "s" : ""} on the pages you analyzed. Click &quot;Analyze&quot; to scan any page and build your site-wide score.
          </p>
          <div className="rounded-2xl border border-gray-100 bg-white overflow-hidden">
            <div className="divide-y divide-gray-100 max-h-96 overflow-y-auto">
              {internalLinks.map((link) => {
                const isCurrentlyAnalyzing = analyzingUrl === link.href;
                let pathname: string;
                try {
                  pathname = new URL(link.href).pathname;
                } catch {
                  pathname = link.href;
                }

                return (
                  <div
                    key={link.href}
                    className="flex items-center justify-between gap-4 px-5 py-3 hover:bg-gray-50 transition-colors"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-sm font-medium text-gray-900">
                        {link.text || pathname}
                      </p>
                      <p className="truncate text-xs text-gray-400">
                        {pathname}
                      </p>
                    </div>
                    <button
                      onClick={() => onAnalyzeLink(link.href)}
                      disabled={isAnalyzing}
                      className="shrink-0 rounded-full bg-purple-500 px-4 py-1.5 text-xs font-bold text-white transition-colors hover:bg-purple-600 disabled:opacity-60"
                    >
                      {isCurrentlyAnalyzing ? (
                        <span className="flex items-center gap-1.5">
                          <svg className="h-3 w-3 animate-spin" viewBox="0 0 24 24" fill="none">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                          </svg>
                          Analyzing...
                        </span>
                      ) : (
                        "Analyze"
                      )}
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="text-center text-xs text-gray-400">
        Analyzed at {new Date(result.fetchedAt).toLocaleString()} | Powered by{" "}
        <a
          href="https://www.sucana.ai"
          className="font-semibold text-purple-500 transition-colors hover:text-purple-600"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sucana AI
        </a>
      </div>
    </section>
  );
}
